### ISSUE TITLE
Potential library issues

### ISSUE THREAD

**Issue by bperrybap** [HendrikVE/Arduino-PCA9633#1]
There may be some support issues due to some in consistences in the library naming used and a potential header file name collision with the pca9633 library.
For example:
- The Arduino library name in .properties is "NXP PCA9633"
- The Arduino IDE library manager will  put the library in a directory name "NXP_PCA9633"
- The main library header file name is "PCA9633.h"
- If a user clones the repository directly into their  Arduino "libraries" directory the directory name is "ArduinoPCA9633"
- PCA9633.h and pca9633.h look the same to Windows

Because of these inconsistencies the name of the directory that is created in the users Arduino sketchbook "libraries" directory will vary depending on how the library is installed and there are some potential issues for Windows users do to a potential header file name collision with the pca9633 library.

I don't have a Windows OS to test this but here is something to be aware of.
Depending on the how the IDE does its header file name collision detection on Windows, there can be an issue when the pca9633 library is also installed.

This is because that library uses a main header name of "pca9633.h" which looks the same as "PCA9633.h" to Windows.
If the IDE does case insensitive file name comparisons on Windows which is likely,
then the IDE will see both as the same which is a collision/duplicate whenever the pca9633 library is installed.
To resolve collisions, the IDE will pick the one in a directory that matches the base header file name, so it will pick the one in the "pca9633" directory which is not the one wanted.

Same thing can potentially happen if cloning the library directly into the libraries directory as the sketchbook library directory name will be "ArduinoPCA9633" 

Same thing can potentially happen if a users does a manual zip install as the library directory name will be "ArduinoPCA9633-master" ,  "ArduinoPCA9633-1.0.2" , etc...

**Comment by HendrikVE** [comment]
> If the IDE does case insensitive file name comparisons on Windows which is likely

I tested it by installing both libraries on a Windows system and it works fine. In fact for sketches, the ArduinoIDE is case sensitive also for Windows as explained [here](https://forum.arduino.cc/index.php?topic=654385.msg4411833#msg4411833). Because of that there won't be a name collision for both libraries.

Furthermore the name of the directory seems to have no importance at all. With all three names (`NXP_PCA9633`, `ArduinoPCA9633`, `ArduinoPCA9633-1.0.2`) the header file will be found, so I don't see any need to change something. The mentioned inconsistency is due to the fact that one is not allowed to use the word "Arduino" in the library name anymore but for github is makes sense to include this in the repository name.

**Comment by bperrybap** [comment]
I guess the IDE itself is now case sensitive when picking the library. That is good.
It didn't use to work that way.
How the IDE selects libraries and their header files has changed quite a bit over the years.
For a while it might pick one directory for the header file and another for the library code that got linked in.
That was real mess.

I did notice some odd behavior with IDEs prior to 1.8.6 and when using .zip file installations.
It seems the library manager can get confused when there are multiple Arduino-PCA9633 libraries installed
This happens if users use .zip installations or manually install them.
Example, install 1.0.1 and 1.0.2 as zip files using the library manager.
Both will end up being install. If you look in the library manager using IDE 1.8.5 it will say that the latest library is version 1.0.1 even though the IDE will compile the sketch with 1.0.2

You may want to put in your readme to tell to avoid using library using .zip files and to use the library manager.
Even when you document it, some will still screw things up.
Every now  and then I get users of my hd44780 library make a mess of things and it is always those that using .zip files.

**Comment by HendrikVE** [comment]
Thank you very much for sharing your experience about your users. I'll add a setup section to my README, but I'm not sure how far back in terms of IDE versions I want to explain this. The Arduino IDE version 1.8.6 was released 2 years ago and I would think that most people updated their IDE in the meantime. Do you have an estimate of how many people might be using even older versions?

**Comment by bperrybap** [comment]
Most people tend to use the latest or just a few revs back. Every now and then somebody will show up using an older version. A few times I've seen some people using REALLY old versions like pre 1.6 and one case clear back to 1.0.1
which came out in 2012.

IDE versions prior to 1.6.9 have to use .zip files which is where the users tend to get into trouble.
There about a half a dozen releases between 1.5 to 1.6.8 that were really terrible and no users should ever use.
If you want to see some more details about various IDE release and some issues you could look at the readme for my hd44780 library
https://github.com/duinoWitchery/hd44780
I have a "S/W Requirements" and a "Installation" section to try to steer users.
But unfortunately, most people seem to be too lazy to read documentation or instructions.
and some users who won't read instructions will install the library using .zip files rather than use the IDE library installer.

I wouldn't worry about it too much. I'd just put in a note in the readme to try to discourage users from using zip files.

**Comment by HendrikVE** [comment]
Thank you, I took your readme as inspiration. I ended up with instructions for IDE 1.6.2+ and advising the user to update their IDE if it's older than that.
