### ISSUE TITLE
Code doesn't compile for AVR platform

### ISSUE THREAD

**Issue by bperrybap** [HendrikVE/Arduino-PCA9633#2]
There are some variable & argument type issues for a few of the Wire functions in the AVR platform that need to be addressed to get the code to compile on that platform.

_deviceAddress should be a **uint8_t** rather than a **uint16_t**

The call: 
`    _wire->requestFrom(_deviceAddres, (uint8_t) 1, true);`

fails on the AVR platform. 
The issue is with the the **true** parameter.
The AVR platform declares that argument to be a **uint8_t** or **int** but in C++ true is a boolean so it fails.
While you could cast the true to be either **uint8_t** or **int**, the default is to send a stop if not explicitly specified so the easiest is to just drop the 3rd parameter.

**Comment by HendrikVE** [comment]
Thank you for bringing this up. I changed `_deviceAddress` to an uint8_t and removed the stop parameter in `requestFrom` as you suggested. It compiles for me now.
